name: 'sample'

services:
  nginx:
    build:
      context: .
      dockerfile: ./build/web/Dockerfile
    image: sample-nginx
    container_name: sample-nginx
    volumes:
      - type: bind
        source: ./front
        target: /app/front
      - type: bind
        source: ./api-gateway
        target: /app/api-gateway
    depends_on:
      - front
      - api-gateway
    ports:
      - 8000:80
    networks:
      - sample-network
  front:
    build:
      context: .
      dockerfile: ./build/front/Dockerfile
    image: sample-front
    container_name: sample-front
    volumes:
      - type: bind
        source: ./front
        target: /app
    depends_on:
      - bdd
    networks:
      - sample-network
  service-auth:
    build:
      context: .
      dockerfile: ./build/service-auth/Dockerfile
    image: sample-service-auth
    container_name: sample-service-auth
    volumes:
      - ./service-auth:/app
    depends_on:
      - bdd
    networks:
      - sample-network
  api-gateway:
    build:
      context: .
      dockerfile: ./build/api-gateway/Dockerfile
      target: development
    image: sample-api-gateway
    container_name: sample-api-gateway
    volumes:
      - ./api-gateway:/app
    depends_on:
      - bdd
      - service-auth
    networks:
      - sample-network
  bdd:
    build:
      context: .
      dockerfile: ./build/bdd/Dockerfile
    image: sample-bdd
    container_name: sample-bdd
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: bdd-volume
        target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: samplebdd
      MYSQL_ROOT_PASSWORD: dzadazdza
      MYSQL_USER: sinyx
      MYSQL_PASSWORD: sinyx
    networks:
      - sample-network

networks:
  sample-network:
    driver: bridge

volumes:
  bdd-volume:
    driver: local
  api-gateway: